### ISSUE TITLE
Just wanted to say good job!

### ISSUE THREAD

**Issue by jcklpe** [jaywick/prime#2]
Hey! I was looking for some alternative file explorers and came across yours and just wanted to say it looks really cool! I am not a real big fan of the Miller Column thing that Finder does but I think your implementation is rad and it's nice to see someone making an alternative Windows system application that ACTUALLY has thoughtful UI! 

I've also been thinking about getting into the UWP stuff, though I think that may be a bit beyond my skill level right now. I'm just a designer learning to code. Anyway just wanted to drop a line and say I was impressed :)

**Comment by jaywick** [comment]
That's really nice of you! Thank you!

Sadly I've had no time to continue with this project, the future of Windows development is definitely UWP and right now [Electron](https://electronjs.org/) is gaining popularity.

> I think that may be a bit beyond my skill level right now

Start off small. Just get a sample project and play around with it!

**Comment by jcklpe** [comment]
I'm def dipping my toes in the Electron pool. So far it's been very basic stuff like modifying extensions built for VScode to suite my purposes but I'm eventually hoping to be able to make a full on app eventually :)
